#!/usr/bin/env python3
"""
High-recall k-mer prefilter for pseudo-haplotype pair SV genotyping.

This script ranks unordered pseudo-haplotype pairs for each SV cluster using
read-local, SV-state informative k-mers. It is intended as a conservative
candidate-reduction gate before pair-wise read realignment and downstream
deep-learning residual scoring.

The input pseudo-haplotype FASTA is expected to be generated by
``bin/construct_haplotypes.py``. FASTA headers must contain fields like:

    SVs=sv1:start-end;sv2:start-end|GT=0:1

The ``SVs`` intervals are 0-based, half-open coordinates on the pseudo-
haplotype sequence. The FASTA basename must encode the cluster interval:

    chrom_start-end.fasta
"""

from __future__ import annotations

import argparse
import csv
import itertools
import os
import re
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path
from typing import DefaultDict, Dict, Iterable, Iterator, List, Optional, Sequence, Set, Tuple

import pysam


DNA_ALPHABET = set("ACGT")
REVCOMP_TABLE = str.maketrans("ACGTacgt", "TGCAtgca")


@dataclass(frozen=True)
class SVInterval:
    """Pseudo-haplotype interval for one SV state."""

    sv_id: str
    start: int
    end: int


@dataclass(frozen=True)
class Haplotype:
    """One generated pseudo-haplotype sequence."""

    hap_id: str
    name: str
    gt: Tuple[int, ...]
    sv_intervals: Tuple[SVInterval, ...]
    sequence: str


@dataclass(frozen=True)
class HapPair:
    """Unordered diploid pseudo-haplotype pair."""

    pair_id: str
    hap1: Haplotype
    hap2: Haplotype


@dataclass(frozen=True)
class Evidence:
    """One k-mer vote for an SV state."""

    sv_index: int
    sv_id: str
    state: int
    weight: float


@dataclass
class ReadEvidence:
    """Read-local evidence accumulated over informative k-mers."""

    support: DefaultDict[int, List[float]] = field(
        default_factory=lambda: defaultdict(lambda: [0.0, 0.0])
    )
    informative_kmers: int = 0

    @property
    def weight(self) -> float:
        """Cap read contribution so highly repetitive evidence cannot dominate."""

        return min(1.0, self.informative_kmers / 20.0)


@dataclass
class ClusterReads:
    """Read sequences and localized query intervals for one cluster."""

    sequences: Dict[str, str]
    intervals: Dict[str, List[Tuple[int, int]]]


@dataclass(frozen=True)
class PairScore:
    """Prefilter result for one candidate pair."""

    rank: int
    pair: HapPair
    score: Optional[float]
    informative_reads: int
    total_read_weight: float
    unexplained_present: float
    unexplained_absent: float
    retained: bool
    reason: str


def reverse_complement(seq: str) -> str:
    """Return reverse complement sequence."""

    return seq.translate(REVCOMP_TABLE)[::-1].upper()


def canonical_kmer(kmer: str) -> str:
    """Return canonical representation of a k-mer."""

    kmer = kmer.upper()
    return min(kmer, reverse_complement(kmer))


def homopolymer_compress(seq: str) -> str:
    """Collapse consecutive identical bases."""

    if not seq:
        return seq

    compressed = [seq[0]]
    for base in seq[1:]:
        if base != compressed[-1]:
            compressed.append(base)
    return "".join(compressed)


def max_homopolymer_run(seq: str) -> int:
    """Return the longest run of one repeated base."""

    if not seq:
        return 0

    best = 1
    current = 1
    for previous, base in zip(seq, seq[1:]):
        if base == previous:
            current += 1
            best = max(best, current)
        else:
            current = 1
    return best


def is_low_complexity(kmer: str) -> bool:
    """Heuristic low-complexity filter for first-pass informative k-mers."""

    unique_bases = set(kmer)
    if len(unique_bases) <= 1:
        return True
    if max(kmer.count(base) for base in unique_bases) / len(kmer) >= 0.8:
        return True
    if max_homopolymer_run(kmer) / len(kmer) >= 0.6:
        return True
    return False


def iter_kmers(
    seq: str,
    k: int,
    canonical: bool = True,
    filter_low_complexity: bool = True,
) -> Iterator[str]:
    """Yield valid k-mers from a sequence."""

    seq = seq.upper()
    if len(seq) < k:
        return

    for start in range(0, len(seq) - k + 1):
        kmer = seq[start : start + k]
        if any(base not in DNA_ALPHABET for base in kmer):
            continue
        if filter_low_complexity and is_low_complexity(kmer):
            continue
        yield canonical_kmer(kmer) if canonical else kmer


def read_fasta(fasta_path: str) -> List[Tuple[str, str]]:
    """Read FASTA records as ``(name, sequence)`` tuples."""

    records: List[Tuple[str, str]] = []
    current_name: Optional[str] = None
    current_parts: List[str] = []

    with open(fasta_path, "r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            if line.startswith(">"):
                if current_name is not None:
                    records.append((current_name, "".join(current_parts).upper()))
                current_name = line[1:].split()[0]
                current_parts = []
            elif current_name is None:
                raise ValueError(f"FASTA sequence found before header in {fasta_path}")
            else:
                current_parts.append(line)

    if current_name is not None:
        records.append((current_name, "".join(current_parts).upper()))
    if not records:
        raise ValueError(f"No FASTA records found in {fasta_path}")
    return records


def parse_header_fields(name: str) -> Dict[str, str]:
    """Parse pipe-delimited FASTA header fields."""

    fields: Dict[str, str] = {}
    for part in name.split("|"):
        key, sep, value = part.partition("=")
        if not sep:
            continue
        fields[key] = value
    return fields


def parse_sv_intervals(value: str) -> Tuple[SVInterval, ...]:
    """Parse ``SVs=sv_id:start-end;...`` header field."""

    intervals: List[SVInterval] = []
    if not value:
        return tuple(intervals)

    for item in value.split(";"):
        if not item:
            continue
        sv_id, sep, coords = item.rpartition(":")
        if not sep:
            raise ValueError(f"Malformed SV interval item: {item}")
        start_text, dash, end_text = coords.partition("-")
        if not dash:
            raise ValueError(f"Malformed SV interval coordinates: {item}")
        intervals.append(SVInterval(sv_id=sv_id, start=int(start_text), end=int(end_text)))
    return tuple(intervals)


def parse_gt(value: str) -> Tuple[int, ...]:
    """Parse ``GT=0:1:...`` state vector."""

    if not value:
        raise ValueError("Missing GT value")
    return tuple(int(item) for item in value.split(":"))


def contig_gt_label(gt: Sequence[int]) -> str:
    """Return compact genotype-state label used as haplotype ID."""

    return "".join(str(state) for state in gt)


def load_haplotypes(fasta_path: str) -> List[Haplotype]:
    """Load pseudo-haplotypes and validate header consistency."""

    haplotypes: List[Haplotype] = []
    sv_ids: Optional[Tuple[str, ...]] = None
    seen_ids: Set[str] = set()

    for name, sequence in read_fasta(fasta_path):
        fields = parse_header_fields(name)
        if "SVs" not in fields or "GT" not in fields:
            raise ValueError(f"FASTA header must contain SVs= and GT= fields: {name}")

        intervals = parse_sv_intervals(fields["SVs"])
        gt = parse_gt(fields["GT"])
        if len(intervals) != len(gt):
            raise ValueError(
                f"Header has {len(intervals)} SV intervals but {len(gt)} GT states: {name}"
            )

        current_sv_ids = tuple(interval.sv_id for interval in intervals)
        if sv_ids is None:
            sv_ids = current_sv_ids
        elif current_sv_ids != sv_ids:
            raise ValueError("All haplotypes in one FASTA must list SVs in the same order")

        hap_id = contig_gt_label(gt)
        if hap_id in seen_ids:
            raise ValueError(f"Duplicate haplotype GT label in FASTA: {hap_id}")
        seen_ids.add(hap_id)

        haplotypes.append(
            Haplotype(
                hap_id=hap_id,
                name=name,
                gt=gt,
                sv_intervals=intervals,
                sequence=sequence,
            )
        )

    return haplotypes


def cluster_interval_from_fasta(fasta_path: str) -> Tuple[str, int, int]:
    """Parse ``chrom_start-end`` from FASTA basename."""

    stem = Path(fasta_path).stem
    match = re.match(r"^(.+)_(\d+)-(\d+)$", stem)
    if not match:
        raise ValueError(
            "FASTA basename must encode cluster interval as chrom_start-end: "
            f"{Path(fasta_path).name}"
        )
    chrom, start, end = match.groups()
    return chrom, int(start), int(end)


def make_pairs(haplotypes: Sequence[Haplotype]) -> List[HapPair]:
    """Generate unordered haplotype pairs, including homozygous/self pairs."""

    pairs: List[HapPair] = []
    for hap1, hap2 in itertools.combinations_with_replacement(haplotypes, 2):
        pair_id = f"{hap1.hap_id}__{hap2.hap_id}"
        pairs.append(HapPair(pair_id=pair_id, hap1=hap1, hap2=hap2))
    return pairs


def interval_context(sequence: str, start: int, end: int, window: int) -> str:
    """Return sequence window around a pseudo-haplotype SV interval."""

    left = max(0, start - window)
    right = min(len(sequence), end + window)
    if left >= right:
        return ""
    return sequence[left:right]


def build_sv_state_kmers(
    haplotypes: Sequence[Haplotype],
    k: int,
    window: int,
    canonical: bool,
    filter_low_complexity: bool,
    hpc: bool,
) -> Dict[int, Dict[int, Set[str]]]:
    """
    Build state-differentiating k-mers for each SV.

    This first implementation uses pseudo-haplotype intervals from FASTA headers.
    For each SV, k-mers observed in state 0 contexts are contrasted with k-mers
    observed in nonzero/present state contexts.
    """

    if not haplotypes:
        raise ValueError("No haplotypes supplied")

    num_svs = len(haplotypes[0].gt)
    raw: Dict[int, Dict[int, Set[str]]] = {
        sv_index: {0: set(), 1: set()} for sv_index in range(num_svs)
    }

    for hap in haplotypes:
        for sv_index, interval in enumerate(hap.sv_intervals):
            state = 0 if hap.gt[sv_index] == 0 else 1
            context = interval_context(hap.sequence, interval.start, interval.end, window)
            if hpc:
                context = homopolymer_compress(context)
            raw[sv_index][state].update(
                iter_kmers(
                    context,
                    k,
                    canonical=canonical,
                    filter_low_complexity=filter_low_complexity,
                )
            )

    state_kmers: Dict[int, Dict[int, Set[str]]] = {}
    for sv_index in range(num_svs):
        absent = raw[sv_index][0] - raw[sv_index][1]
        present = raw[sv_index][1] - raw[sv_index][0]
        state_kmers[sv_index] = {0: absent, 1: present}

    return state_kmers


def build_kmer_to_evidence(
    haplotypes: Sequence[Haplotype],
    state_kmers: Dict[int, Dict[int, Set[str]]],
    absent_weight: float,
    present_weight: float,
) -> Dict[str, List[Evidence]]:
    """Build inverted k-mer evidence index."""

    sv_ids = [interval.sv_id for interval in haplotypes[0].sv_intervals]
    kmer_to_evidence: DefaultDict[str, List[Evidence]] = defaultdict(list)

    for sv_index, by_state in state_kmers.items():
        for state, kmers in by_state.items():
            weight = absent_weight if state == 0 else present_weight
            for kmer in kmers:
                kmer_to_evidence[kmer].append(
                    Evidence(
                        sv_index=sv_index,
                        sv_id=sv_ids[sv_index],
                        state=state,
                        weight=weight,
                    )
                )

    return dict(kmer_to_evidence)


def query_interval_from_record(
    record: pysam.AlignedSegment,
    ref_start: int,
    ref_end: int,
) -> Optional[Tuple[int, int]]:
    """Map a reference interval overlap to query coordinates for one alignment."""

    if record.cigartuples is None or record.reference_start is None:
        return None

    ref_pos = record.reference_start
    query_pos = 0
    query_starts: List[int] = []
    query_ends: List[int] = []

    for op, length in record.cigartuples:
        consumes_ref = op in (0, 2, 3, 7, 8)
        consumes_query = op in (0, 1, 4, 5, 7, 8)

        if op in (0, 7, 8):
            block_start = ref_pos
            block_end = ref_pos + length
            overlap_start = max(block_start, ref_start)
            overlap_end = min(block_end, ref_end)
            if overlap_start < overlap_end:
                query_starts.append(query_pos + (overlap_start - block_start))
                query_ends.append(query_pos + (overlap_end - block_start))

        if consumes_ref:
            ref_pos += length
        if consumes_query:
            query_pos += length

    if not query_starts:
        return None
    return min(query_starts), max(query_ends)


def nearby_large_query_segments(
    record: pysam.AlignedSegment,
    ref_start: int,
    ref_end: int,
    large_ins_threshold: int,
    softclip_threshold: int,
) -> List[Tuple[int, int]]:
    """Collect large insertion or soft-clip query segments near the cluster interval."""

    if record.cigartuples is None or record.reference_start is None:
        return []

    ref_pos = record.reference_start
    query_pos = 0
    segments: List[Tuple[int, int]] = []

    for op, length in record.cigartuples:
        consumes_ref = op in (0, 2, 3, 7, 8)
        consumes_query = op in (0, 1, 4, 5, 7, 8)

        if op == 1 and length >= large_ins_threshold:
            if ref_start <= ref_pos <= ref_end:
                segments.append((query_pos, query_pos + length))
        elif op == 4 and length >= softclip_threshold:
            clip_is_near_left = abs(ref_pos - ref_start) <= softclip_threshold
            clip_is_near_right = abs(ref_pos - ref_end) <= softclip_threshold
            clip_inside = ref_start <= ref_pos <= ref_end
            if clip_inside or clip_is_near_left or clip_is_near_right:
                segments.append((query_pos, query_pos + length))

        if consumes_ref:
            ref_pos += length
        if consumes_query:
            query_pos += length

    return segments


def merge_intervals(intervals: Iterable[Tuple[int, int]], flank: int, sequence_length: int) -> List[Tuple[int, int]]:
    """Merge query intervals after adding a flank."""

    expanded = [
        (max(0, start - flank), min(sequence_length, end + flank))
        for start, end in intervals
        if start < end
    ]
    if not expanded:
        return []

    expanded.sort()
    merged = [expanded[0]]
    for start, end in expanded[1:]:
        last_start, last_end = merged[-1]
        if start <= last_end:
            merged[-1] = (last_start, max(last_end, end))
        else:
            merged.append((start, end))
    return merged


def record_sequence_priority(record: pysam.AlignedSegment) -> Tuple[int, int, int]:
    """Rank records for recovering one representative read sequence."""

    sequence_length = len(record.query_sequence) if record.query_sequence else 0
    primary_rank = 1 if not record.is_secondary and not record.is_supplementary else 0
    return primary_rank, sequence_length, record.mapping_quality


def collect_cluster_reads(
    bam_path: str,
    chrom: str,
    ref_start: int,
    ref_end: int,
    large_ins_threshold: int,
    softclip_threshold: int,
) -> ClusterReads:
    """Collect full read sequences and local query intervals from the original BAM."""

    read_sequences: Dict[str, str] = {}
    read_priorities: Dict[str, Tuple[int, int, int]] = {}
    read_intervals: DefaultDict[str, List[Tuple[int, int]]] = defaultdict(list)

    with pysam.AlignmentFile(bam_path, "rb") as bam:
        for record in bam.fetch(chrom, ref_start, ref_end):
            if record.is_unmapped or not record.query_name:
                continue

            sequence = record.query_sequence
            if sequence:
                priority = record_sequence_priority(record)
                if priority > read_priorities.get(record.query_name, (-1, -1, -1)):
                    read_sequences[record.query_name] = sequence.upper()
                    read_priorities[record.query_name] = priority

            mapped_interval = query_interval_from_record(record, ref_start, ref_end)
            if mapped_interval is not None:
                read_intervals[record.query_name].append(mapped_interval)
            read_intervals[record.query_name].extend(
                nearby_large_query_segments(
                    record,
                    ref_start,
                    ref_end,
                    large_ins_threshold=large_ins_threshold,
                    softclip_threshold=softclip_threshold,
                )
            )

    return ClusterReads(sequences=read_sequences, intervals=dict(read_intervals))


def build_read_evidence(
    cluster_reads: ClusterReads,
    kmer_to_evidence: Dict[str, List[Evidence]],
    k: int,
    query_flank: int,
    min_info_kmers: int,
    canonical: bool,
    filter_low_complexity: bool,
    hpc: bool,
) -> Dict[str, ReadEvidence]:
    """Extract local read k-mers and accumulate SV-state evidence."""

    read_evidence: Dict[str, ReadEvidence] = {}
    for read_name, intervals in cluster_reads.intervals.items():
        sequence = cluster_reads.sequences.get(read_name)
        if not sequence:
            continue
        local_intervals = merge_intervals(intervals, query_flank, len(sequence))
        if not local_intervals:
            continue

        local_kmers: Set[str] = set()
        for start, end in local_intervals:
            local_sequence = sequence[start:end]
            if hpc:
                local_sequence = homopolymer_compress(local_sequence)
            local_kmers.update(
                iter_kmers(
                    local_sequence,
                    k,
                    canonical=canonical,
                    filter_low_complexity=filter_low_complexity,
                )
            )

        evidence = ReadEvidence()
        for kmer in local_kmers:
            votes = kmer_to_evidence.get(kmer)
            if not votes:
                continue
            evidence.informative_kmers += 1
            for vote in votes:
                evidence.support[vote.sv_index][vote.state] += vote.weight

        if evidence.informative_kmers >= min_info_kmers:
            read_evidence[read_name] = evidence

    return read_evidence


def haplotype_compatibility(haplotype: Haplotype, evidence: ReadEvidence) -> float:
    """Compute positive read compatibility for one haplotype."""

    score = 0.0
    for sv_index, support in evidence.support.items():
        state = 0 if haplotype.gt[sv_index] == 0 else 1
        score += support[state]
    return score


def unexplained_evidence(pair: HapPair, evidence: ReadEvidence) -> Tuple[float, float]:
    """Summarize evidence contradicted by both haplotypes in a pair."""

    unexplained_present = 0.0
    unexplained_absent = 0.0
    for sv_index, support in evidence.support.items():
        dosage = int(pair.hap1.gt[sv_index] != 0) + int(pair.hap2.gt[sv_index] != 0)
        if dosage == 0:
            unexplained_present += support[1]
        elif dosage == 2:
            unexplained_absent += support[0]
    return unexplained_present, unexplained_absent


def score_pair(pair: HapPair, read_evidence: Dict[str, ReadEvidence]) -> PairScore:
    """Score one candidate pair by read-level best-haplotype compatibility."""

    score = 0.0
    informative_reads = 0
    total_read_weight = 0.0
    unexplained_present = 0.0
    unexplained_absent = 0.0

    for evidence in read_evidence.values():
        read_weight = evidence.weight
        hap1_score = haplotype_compatibility(pair.hap1, evidence)
        hap2_score = haplotype_compatibility(pair.hap2, evidence)
        best_score = max(hap1_score, hap2_score)
        if best_score == 0:
            continue

        present, absent = unexplained_evidence(pair, evidence)
        score += read_weight * best_score
        unexplained_present += read_weight * present
        unexplained_absent += read_weight * absent
        informative_reads += 1
        total_read_weight += read_weight

    return PairScore(
        rank=0,
        pair=pair,
        score=score,
        informative_reads=informative_reads,
        total_read_weight=total_read_weight,
        unexplained_present=unexplained_present,
        unexplained_absent=unexplained_absent,
        retained=False,
        reason="scored",
    )


def select_scored_pairs(
    scores: Sequence[PairScore],
    keep_top: int,
) -> List[PairScore]:
    """Select retained pairs after scoring."""

    keep = min(keep_top, len(scores))
    selected: List[PairScore] = []
    for rank, score in enumerate(scores[:keep], start=1):
        selected.append(
            PairScore(
                rank=rank,
                pair=score.pair,
                score=score.score,
                informative_reads=score.informative_reads,
                total_read_weight=score.total_read_weight,
                unexplained_present=score.unexplained_present,
                unexplained_absent=score.unexplained_absent,
                retained=True,
                reason=f"top_{keep}",
            )
        )
    return selected


def bypass_pairs(pairs: Sequence[HapPair]) -> List[PairScore]:
    """Return all pairs without k-mer scoring."""

    return [
        PairScore(
            rank=rank,
            pair=pair,
            score=None,
            informative_reads=0,
            total_read_weight=0.0,
            unexplained_present=0.0,
            unexplained_absent=0.0,
            retained=True,
            reason="bypass_total_pairs_le_threshold",
        )
        for rank, pair in enumerate(pairs, start=1)
    ]


def score_pairs(pairs: Sequence[HapPair], read_evidence: Dict[str, ReadEvidence]) -> List[PairScore]:
    """Score and sort all candidate pairs."""

    scores = [score_pair(pair, read_evidence) for pair in pairs]
    scores.sort(
        key=lambda result: (
            -float(result.score or 0.0),
            result.unexplained_present,
            result.unexplained_absent,
            -result.informative_reads,
            result.pair.pair_id,
        )
    )
    return scores


def summarize_sv_evidence(
    haplotypes: Sequence[Haplotype],
    state_kmers: Dict[int, Dict[int, Set[str]]],
    read_evidence: Dict[str, ReadEvidence],
) -> List[Dict[str, object]]:
    """Build per-SV evidence summary rows."""

    rows: List[Dict[str, object]] = []
    sv_ids = [interval.sv_id for interval in haplotypes[0].sv_intervals]
    for sv_index, sv_id in enumerate(sv_ids):
        absent_support = 0.0
        present_support = 0.0
        absent_reads = 0
        present_reads = 0
        for evidence in read_evidence.values():
            support = evidence.support.get(sv_index)
            if not support:
                continue
            absent_support += support[0]
            present_support += support[1]
            absent_reads += int(support[0] > 0)
            present_reads += int(support[1] > 0)

        rows.append(
            {
                "sv_index": sv_index,
                "sv_id": sv_id,
                "absent_kmers": len(state_kmers[sv_index][0]),
                "present_kmers": len(state_kmers[sv_index][1]),
                "absent_support": f"{absent_support:.6g}",
                "present_support": f"{present_support:.6g}",
                "absent_reads": absent_reads,
                "present_reads": present_reads,
            }
        )
    return rows


def write_tsv(path: str, rows: Sequence[Dict[str, object]], fields: Sequence[str]) -> None:
    """Write rows to a tab-delimited file."""

    with open(path, "w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, delimiter="\t")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def wrap_sequence(sequence: str, width: int = 80) -> Iterator[str]:
    """Yield wrapped FASTA sequence lines."""

    for start in range(0, len(sequence), width):
        yield sequence[start : start + width]


def write_cluster_reads_fasta(cluster_reads: ClusterReads, path: str) -> None:
    """Write one deduplicated full-read FASTA for downstream alignment."""

    with open(path, "w", encoding="utf-8") as handle:
        for read_name in sorted(cluster_reads.sequences):
            handle.write(f">{read_name}\n")
            for line in wrap_sequence(cluster_reads.sequences[read_name]):
                handle.write(line + "\n")


def retained_haplotypes(scores: Sequence[PairScore]) -> List[Haplotype]:
    """Return unique haplotypes appearing in retained pairs, preserving rank order."""

    retained: List[Haplotype] = []
    seen: Set[str] = set()
    for score in scores:
        for haplotype in (score.pair.hap1, score.pair.hap2):
            if haplotype.hap_id in seen:
                continue
            retained.append(haplotype)
            seen.add(haplotype.hap_id)
    return retained


def write_retained_haplotype_fastas(
    haplotypes: Sequence[Haplotype],
    cluster_dir: str,
) -> List[Dict[str, object]]:
    """Write one single-contig FASTA per retained haplotype."""

    hap_fasta_dir = os.path.join(cluster_dir, "hap_fastas")
    os.makedirs(hap_fasta_dir, exist_ok=True)

    rows: List[Dict[str, object]] = []
    for haplotype in haplotypes:
        fasta_path = os.path.join(hap_fasta_dir, f"{haplotype.hap_id}.fasta")
        with open(fasta_path, "w", encoding="utf-8") as handle:
            handle.write(f">{haplotype.name}\n")
            for line in wrap_sequence(haplotype.sequence):
                handle.write(line + "\n")

        rows.append(
            {
                "hap_id": haplotype.hap_id,
                "gt": ":".join(str(state) for state in haplotype.gt),
                "hap_fasta": os.path.relpath(fasta_path, cluster_dir),
                "contig_name": haplotype.name,
                "length": len(haplotype.sequence),
            }
        )

    return rows


def pair_score_rows(scores: Sequence[PairScore], total_pairs: int, prefilter_applied: bool) -> List[Dict[str, object]]:
    """Convert pair scores to TSV rows."""

    rows: List[Dict[str, object]] = []
    for result in scores:
        rows.append(
            {
                "rank": result.rank,
                "pair_id": result.pair.pair_id,
                "hap1_id": result.pair.hap1.hap_id,
                "hap2_id": result.pair.hap2.hap_id,
                "hap1_gt": ":".join(str(state) for state in result.pair.hap1.gt),
                "hap2_gt": ":".join(str(state) for state in result.pair.hap2.gt),
                "score": "NA" if result.score is None else f"{result.score:.8g}",
                "informative_reads": result.informative_reads,
                "total_read_weight": f"{result.total_read_weight:.6g}",
                "unexplained_present": f"{result.unexplained_present:.6g}",
                "unexplained_absent": f"{result.unexplained_absent:.6g}",
                "retained": str(result.retained).lower(),
                "reason": result.reason,
                "prefilter_applied": str(prefilter_applied).lower(),
                "total_pairs": total_pairs,
            }
        )
    return rows


def haplotype_rows(haplotypes: Sequence[Haplotype]) -> List[Dict[str, object]]:
    """Convert haplotypes to TSV rows."""

    rows: List[Dict[str, object]] = []
    for hap in haplotypes:
        rows.append(
            {
                "hap_id": hap.hap_id,
                "gt": ":".join(str(state) for state in hap.gt),
                "name": hap.name,
                "length": len(hap.sequence),
            }
        )
    return rows


def read_evidence_rows(read_evidence: Dict[str, ReadEvidence], haplotypes: Sequence[Haplotype]) -> List[Dict[str, object]]:
    """Convert read evidence to long-form TSV rows."""

    sv_ids = [interval.sv_id for interval in haplotypes[0].sv_intervals]
    rows: List[Dict[str, object]] = []
    for read_name, evidence in sorted(read_evidence.items()):
        for sv_index, support in sorted(evidence.support.items()):
            rows.append(
                {
                    "read_id": read_name,
                    "sv_index": sv_index,
                    "sv_id": sv_ids[sv_index],
                    "absent_support": f"{support[0]:.6g}",
                    "present_support": f"{support[1]:.6g}",
                    "informative_kmers": evidence.informative_kmers,
                    "read_weight": f"{evidence.weight:.6g}",
                }
            )
    return rows


def discover_fasta_paths(path: str) -> List[str]:
    """Return FASTA input paths from one file or a directory."""

    if os.path.isdir(path):
        fasta_paths = [
            os.path.join(path, name)
            for name in os.listdir(path)
            if name.endswith((".fa", ".fasta", ".fna"))
        ]
        return sorted(fasta_paths)
    return [path]


def process_cluster(fasta_path: str, args: argparse.Namespace) -> None:
    """Run prefilter for one pseudo-haplotype FASTA cluster."""

    cluster_name = Path(fasta_path).stem
    cluster_dir = os.path.join(args.out_dir, cluster_name)
    os.makedirs(cluster_dir, exist_ok=True)

    haplotypes = load_haplotypes(fasta_path)
    pairs = make_pairs(haplotypes)
    total_pairs = len(pairs)
    chrom, ref_start, ref_end = cluster_interval_from_fasta(fasta_path)
    cluster_reads = collect_cluster_reads(
        args.bam,
        chrom,
        ref_start,
        ref_end,
        large_ins_threshold=args.large_ins_threshold,
        softclip_threshold=args.softclip_threshold,
    )
    reads_fasta_path = os.path.join(cluster_dir, "cluster_reads.fasta")
    write_cluster_reads_fasta(cluster_reads, reads_fasta_path)

    write_tsv(
        os.path.join(cluster_dir, "haplotypes.tsv"),
        haplotype_rows(haplotypes),
        fields=("hap_id", "gt", "name", "length"),
    )

    if total_pairs <= args.prefilter_pair_threshold:
        retained = bypass_pairs(pairs)
        prefilter_applied = False
        read_evidence: Dict[str, ReadEvidence] = {}
        state_kmers = {
            sv_index: {0: set(), 1: set()} for sv_index in range(len(haplotypes[0].gt))
        }
    else:
        state_kmers = build_sv_state_kmers(
            haplotypes,
            k=args.k,
            window=args.sv_window,
            canonical=not args.no_canonical,
            filter_low_complexity=not args.keep_low_complexity,
            hpc=args.homopolymer_compress,
        )
        kmer_to_evidence = build_kmer_to_evidence(
            haplotypes,
            state_kmers,
            absent_weight=args.absent_weight,
            present_weight=args.present_weight,
        )
        read_evidence = build_read_evidence(
            cluster_reads,
            kmer_to_evidence,
            k=args.k,
            query_flank=args.query_flank,
            min_info_kmers=args.min_info_kmers,
            canonical=not args.no_canonical,
            filter_low_complexity=not args.keep_low_complexity,
            hpc=args.homopolymer_compress,
        )
        scores = score_pairs(pairs, read_evidence)
        retained = select_scored_pairs(
            scores,
            keep_top=args.keep_top_pairs,
        )
        prefilter_applied = True

    pair_rows = pair_score_rows(retained, total_pairs=total_pairs, prefilter_applied=prefilter_applied)
    write_tsv(
        os.path.join(cluster_dir, "prefilter_pairs.tsv"),
        pair_rows,
        fields=(
            "rank",
            "pair_id",
            "hap1_id",
            "hap2_id",
            "hap1_gt",
            "hap2_gt",
            "score",
            "informative_reads",
            "total_read_weight",
            "unexplained_present",
            "unexplained_absent",
            "retained",
            "reason",
            "prefilter_applied",
            "total_pairs",
        ),
    )

    retained_haps = retained_haplotypes(retained)
    retained_hap_rows = write_retained_haplotype_fastas(retained_haps, cluster_dir)
    write_tsv(
        os.path.join(cluster_dir, "retained_haplotypes.tsv"),
        retained_hap_rows,
        fields=("hap_id", "gt", "hap_fasta", "contig_name", "length"),
    )

    write_tsv(
        os.path.join(cluster_dir, "sv_evidence.tsv"),
        summarize_sv_evidence(haplotypes, state_kmers, read_evidence),
        fields=(
            "sv_index",
            "sv_id",
            "absent_kmers",
            "present_kmers",
            "absent_support",
            "present_support",
            "absent_reads",
            "present_reads",
        ),
    )

    if args.write_read_evidence and read_evidence:
        write_tsv(
            os.path.join(cluster_dir, "read_evidence.tsv"),
            read_evidence_rows(read_evidence, haplotypes),
            fields=(
                "read_id",
                "sv_index",
                "sv_id",
                "absent_support",
                "present_support",
                "informative_kmers",
                "read_weight",
            ),
        )

    with open(os.path.join(cluster_dir, "prefilter.log"), "w", encoding="utf-8") as handle:
        handle.write(f"fasta\t{fasta_path}\n")
        handle.write(f"bam\t{args.bam}\n")
        handle.write(f"cluster_reads_fasta\t{reads_fasta_path}\n")
        handle.write(f"haplotypes\t{len(haplotypes)}\n")
        handle.write(f"total_pairs\t{total_pairs}\n")
        handle.write(f"prefilter_pair_threshold\t{args.prefilter_pair_threshold}\n")
        handle.write(f"keep_top_pairs\t{args.keep_top_pairs}\n")
        handle.write(f"prefilter_applied\t{str(prefilter_applied).lower()}\n")
        handle.write(f"retained_pairs\t{len(retained)}\n")
        handle.write(f"retained_haplotypes\t{len(retained_haps)}\n")
        handle.write(f"cluster_reads\t{len(cluster_reads.sequences)}\n")
        handle.write(f"informative_reads\t{len(read_evidence)}\n")
        handle.write(f"k\t{args.k}\n")

    print(
        f"{cluster_name}: haplotypes={len(haplotypes)} total_pairs={total_pairs} "
        f"prefilter={str(prefilter_applied).lower()} retained={len(retained)}"
    )


def process_cluster_worker(task: Tuple[str, argparse.Namespace]) -> None:
    """Multiprocessing worker for one cluster FASTA."""

    fasta_path, args = task
    process_cluster(fasta_path, args)


def build_arg_parser() -> argparse.ArgumentParser:
    """Build CLI parser."""

    parser = argparse.ArgumentParser(
        description=(
            "High-recall read-local k-mer prefilter for pseudo-haplotype pairs. "
            "Input FASTA can be one cluster FASTA or a directory of cluster FASTAs."
        )
    )
    parser.add_argument("--fasta", required=True, help="Pseudo-haplotype FASTA file or directory")
    parser.add_argument("--bam", required=True, help="Original reference-aligned BAM")
    parser.add_argument("--out-dir", required=True, help="Output directory")
    parser.add_argument("--k", type=int, default=21, help="k-mer length (default: 21)")
    parser.add_argument("--sv-window", type=int, default=250, help="Sequence flank around SV interval for state k-mers")
    parser.add_argument("--query-flank", type=int, default=3000, help="Query flank around localized cluster interval")
    parser.add_argument("--min-info-kmers", type=int, default=5, help="Minimum informative k-mers required per read")
    parser.add_argument("--large-ins-threshold", type=int, default=50, help="Large insertion CIGAR threshold")
    parser.add_argument("--softclip-threshold", type=int, default=50, help="Large soft-clip CIGAR threshold")
    parser.add_argument("--absent-weight", type=float, default=0.5, help="Weight for absent/reference evidence")
    parser.add_argument("--present-weight", type=float, default=1.0, help="Weight for present/ALT evidence")
    parser.add_argument("--prefilter-pair-threshold", type=int, default=30, help="Bypass prefilter at or below this pair count")
    parser.add_argument("--keep-top-pairs", type=int, default=30, help="Number of top scored pairs to retain after prefiltering")
    parser.add_argument("--homopolymer-compress", action="store_true", help="Apply homopolymer compression before k-mer extraction")
    parser.add_argument("--no-canonical", action="store_true", help="Do not canonicalize reverse-complement k-mers")
    parser.add_argument("--keep-low-complexity", action="store_true", help="Keep low-complexity k-mers")
    parser.add_argument("--write-read-evidence", action="store_true", help="Write long-form read evidence TSV")
    parser.add_argument("--threads", type=int, default=1, help="Number of cluster-level worker processes")
    return parser


def validate_args(args: argparse.Namespace) -> None:
    """Validate CLI arguments."""

    if args.k <= 0:
        raise ValueError("--k must be positive")
    if args.prefilter_pair_threshold < 0:
        raise ValueError("--prefilter-pair-threshold must be non-negative")
    if args.keep_top_pairs <= 0:
        raise ValueError("--keep-top-pairs must be positive")
    if args.threads <= 0:
        raise ValueError("--threads must be positive")


def main() -> None:
    """CLI entry point."""

    args = build_arg_parser().parse_args()
    validate_args(args)
    os.makedirs(args.out_dir, exist_ok=True)

    fasta_paths = discover_fasta_paths(args.fasta)
    if not fasta_paths:
        raise ValueError(f"No FASTA files found from input: {args.fasta}")

    if args.threads == 1:
        for fasta_path in fasta_paths:
            process_cluster(fasta_path, args)
    else:
        tasks = [(fasta_path, args) for fasta_path in fasta_paths]
        with ProcessPoolExecutor(max_workers=args.threads) as executor:
            list(executor.map(process_cluster_worker, tasks))


if __name__ == "__main__":
    main()
